version: '3.4'

services:
  businfo.api:
    image: ${DOCKER_REGISTRY}businfoapi
    build:
      context: .
      dockerfile: BusInfo.API/Dockerfile

  businfo.web:
    image: ${DOCKER_REGISTRY}businfoweb
    build:
      context: .
      dockerfile: BusInfo.Web/Dockerfile

